name: Dutch
version: "1.3.24"
slug: dutch
description: Local multiplayer Dutch card game
url: https://github.com/gabbro246/dutch-haos/tree/main/dutch
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
init: false
stage: stable
webui: http://[HOST]:[PORT:3000]
watchdog: tcp://[HOST]:[PORT:3000]
map:
  - share:rw
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: Dutch web UI
options:
  game_log_dir: /share/dutch/logs
schema:
  game_log_dir: str
